babel-utils/babel-plugin-tester

- README.md
- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/index.js
- src/index.js
This removes `modifier` in favor of `only` and `skip` which are more straightforward. `modifier` was never documented.
BREAKING CHANGE: `modifier` has been removed, use `only` and `skip` instead
> feat(tests): add `only` and `skip`, remove `modifier`

- README.md
- package.json
- src/index.js
- yarn.lock
I'm not sure why these were the default, but they cause Babel plugins to behave differently and to turn them off is difficult so I've just removed them.
> Remove recast

- .all-contributorsrc
- README.md
- package.json
- src/__tests__/index.js
- src/index.js
**What**:
Provides the ability to pass plugin options at the tester and test level.
Also added associated tests and documentation. 
**Why**:
I wanted to be able to test certain functionality not enabled by default
**How**:
- Added tests 😉 
- Added option to main start
- Updated test config to overwrite main option
> Added ability to pass plugin options

- README.md
- src/__tests__/index.js
- src/index.js
**What**: Adds a `formatResult` option
**Why**: So people can format the snapshot with `prettier` or `prettier-eslint` if they want to.
**How**: apply `formatResult` function (defaults to an identity function) to the `result`.
> feat(formatResult): add `formatResult` option

- src/__tests__/index.js
- src/index.js
This was super annoying. Any time I added/moved/removed a test, all the
snapshots would need updating because the title for every one of them
changed. Pretty annoying. So now we only use the number for untitled
tests and we only increment it for the untitled tests.
This is going to be a major version bump.
> feat(test-numbers): only use numbers for tests without titles

- package.json
Make compatible with babel 7
Currently, because babel-core is defined as a regular dependency - it prevents babel 7 usage. 
Also, please see: 
- https://github.com/facebook/jest/pull/4557/files
- https://github.com/babel/babel-bridge
Just a change to `package.json`
> move babel-core to peerDependencies

- src/index.js
**Why**:
I'd like to run fixture tests for both babel@6 and babel@7, so I have to save `output.js` under i.e. `output6.js` and `output7.js`.
> feat: Accept fixtureOutputName option for fixtures mode

- package.json
- src/__tests__/fixtures/fixtures/without-output-file/code.js
- src/__tests__/index.js
- src/index.js
**Why**:
So fixtures mode works more like snapshots - if output is absent, just create it.
> feat: Create automatically fixtures output.js files for new tests

- src/index.js
Followup to [this](https://github.com/babel-utils/babel-plugin-tester/pull/28#discussion_r194244833) - although I'm not sure if this is what you were talking about.
> chore: Fixture failure message matching the output filename

- src/__tests__/fixtures/fixtures/typescript/code.ts
- src/__tests__/index.js
- src/index.js
**What**:
Support typescript file extensions when running automated fixtures tests
**Why**:
Made a babel plugin with typescript support and would like to run automated fixture tests on `.ts` files with this neat tester
> Add typescript file extension support

- src/index.js
**What**: babel-core was being imported in index.js so it can be used as a default parameter for pluginTester().  The result of this is that if a custom babel is passed into the function, babel-core will still be imported.  By moving the this functionality into a require() statement in the default parameter declaration we can stop index.js from requiring the module when it is not being used.  
**Why**:  Since babel-core is a peer dependency, it won't be installed if a dependent project doesn't use it as a dependency.  This will cause errors in a project that uses a different or custom version of babel/core.  
For example:
```js
pluginTester = require('babel-plugin-tester');
pluginTester({
babel: require('@babel/core'),
...
});
```
Causes the following error
```js
Error: Cannot find module …
```
> change babel-core import to optional require in default param

- README.md
Hi - I have been using babel-plugin-tester for a bit with my own plugins (LOVE IT!).  I discovered today that it already works with `babel.config.js`, but wanted to update the documentation for anyone else who runs into this problem.  The only changes are to README.md, no actual code changes.
Thanks!
PS I did not add myself to .all-contributorsrc because I haven't made any code changes, if you would prefer that I do this, please let me know.
> Add documentation for working with babel.config.js

- .all-contributorsrc
- README.md
- package.json
- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/index.js
- src/index.js
**What**:
Allowing expected `output` to be an empty string.
**Why**:
There's cases when we just want to verify that a node gets removed.
**How**:
By removing the default behaviour of keeping `output` to be an empty string, and instead make it `undefined` if it isn't provided.
Bonus commits:
* Added a eslint rule to deny trailing semi colons.
* Upgraded kcd-scripts to make `npm run add-contributor` to work.
> Empty output

- package.json
- src/__mocks__/@babel/core.js
- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/index.js
- src/index.js
**What**:
Babel packages, kcd-scripts also, have all been upgraded. Failing tests have been fixed
**Why**:
`babel-plugin-helper` wasn't working with babel 7 without babel bridge.
**How**:
I've first upgraded dependencies. And then tried to fix errors that were caused due to babel 6 and 7 incompatibilities.
> Fix failing tests upon upgrade

- .all-contributorsrc
- README.md
- src/__tests__/index.js
- src/index.js
**What**: This modifies the `describe` blocks generated by the tester to avoid returning promises.
**Why**: Even though this use case is "correct", using `async` functions in `describe` blocks (or returning promises, in general) is a common programmer error as Jest doesn't allow tests to be defined asychronously. Jest >=24.3.0 starts warning against this (https://github.com/facebook/jest/pull/7852) and it will be an error in Jest 25. This makes the necessary changes to avoid the warning and a possible future error, while maintaining the same external API
**How**: I removed the return values for the `describe` blocks and updated all tests to mimic how Jest collects tests to wait for them to finish (instead of awaiting the promise we were returning previously).
Disclaimer: I'm a Jest core …
> Avoid returning values in describe blocks

- src/__tests__/fixtures/fixtures/options.json
- src/__tests__/index.js
- src/index.js
**What**: Fixing options from root `options.json` not getting loaded
**Why**: The options should be loaded when specified in the root fixtures directory, currently they are not.
**How**: Checks if the current `fixturesDir` contains a `options.json` file and adds it to the plugin options.
> fix(fixtures): get options from root options.json

- README.md
- package.json
- src/__tests__/index.js
- src/index.js
**What**: `babelOptions.plugins` cannot be used together with fixture tests, as the plugin config gets overridden.
**Why**: To allow setups like:
```js
pluginTester({
plugin: myPlugin,
fixtures: join(__dirname, '__fixtures__'),
babelOptions: {
plugins: ['@babel/plugin-syntax-class-properties']
}
});
```
```js
// __fixtures__/example/options.json
{
"foo": "bar"
}
```
**How**: Replaced `lodash.merge` with [`lodash.mergeWith`](https://lodash.com/docs/4.17.11#mergeWith) with the following `customizer`:
```js
function mergeCustomizer(objValue, srcValue) {
if (Array.isArray(objValue)) {
return objValue.concat(srcValue)
}
return undefined
}
```
I found the test setup a bit confusing, but I hope that I added a good test scenario.
> fix: concat arrays in `babelOptions`

- src/__tests__/index.js
- src/index.js
**What**:
Fixed `babel-plugin-tester` not trimming strings correctly
**Why**:
When using a formatter that adds an empty line at the end of the string `babel-plugin-tester` will save the result with this empty line. In subsequent runs, when reading the output file it trims it off, causing the strings to not match.
**How**:
Call trim at assert.equal for both values and don't trim code passed to formatResult
> fix: trim input and output correctly

- package.json
- src/__tests__/fixtures/fixtures/jsx-support/.babelrc
- src/__tests__/fixtures/fixtures/jsx-support/code.jsx
- src/__tests__/fixtures/fixtures/tsx-support/.babelrc
- src/__tests__/fixtures/fixtures/tsx-support/code.tsx
- src/__tests__/index.js
- src/index.js
**What**: Added support for .jsx files in fixtures
**Why**: Babel plugin can manage .jsx
**How**: Some code changes
> Feat: adds jsx support

- package.json
- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/index.js
- src/index.js
**What**:
Removed unnecessary packages `path-exists`, `common-tags`, and `invariant`
**Why**:
- `path-exists`: Node has `fs.existsSync` that does the same task, the package even advises using it instead
> NOTE: fs.existsSync has been un-deprecated in Node.js since 6.8.0. If you only need to check synchronously, this module is not needed.
https://github.com/sindresorhus/path-exists
- `common-tags`: Downloading a [5.6kB](https://bundlephobia.com/result?p=common-tags@1.8.0) package to make our errors single line is unnecessary
- `invariant`: Node has `assert` which does the same job and is used elsewhere in the code
**How**:
- `path-exists`: Replaced with `fs.existsSync`
- `common-tags`: Removed the linebreaks from the strings we were using `oneLine` on
- `invariant`: Replaced with `assert`
> fix: remove unnecessary packages

- src/__tests__/fixtures/fixtures/babelrc/cjs/.babelrc.cjs
- src/__tests__/fixtures/fixtures/babelrc/cjs/code.jsx
- src/__tests__/fixtures/fixtures/babelrc/js/.babelrc.js
- src/__tests__/fixtures/fixtures/babelrc/js/code.jsx
- src/__tests__/fixtures/fixtures/babelrc/normal/.babelrc
- src/__tests__/fixtures/fixtures/babelrc/normal/code.jsx
- src/__tests__/index.js
- src/index.js
**What**:
Check for `js` and `cjs` version of `.babelrc`
**Why**:
Babel supports `.babelrc.js` and `.babelrc.cjs`
> File-relative configuration
.babelrc (and .babelrc.js or .babelrc.cjs) files
https://babeljs.io/docs/en/config-files
**How**:
Extend the check for `.babelrc` to include `.babelrc.js` and `.babelrc.cjs`
> fix: check for js and cjs version of babelrc

- src/index.js
**What**:
Don't add the snapshotSerializer if `expect` isn't defined
**Why**:
Crashes in non-jest environments (https://app.circleci.com/jobs/github/mui-org/material-ui/129232)
**How**:
Guard with `typeof expect`
> fix: Crash when importing without global expect

- src/plugin-tester.js
This is an updated version of #47 
Thank you @yuyaryshev
> fix: apply fix line endings to code and output in two spots

- README.md
- src/__tests__/fixtures/fixtures/fixtureOutputExt/code.ts
- src/__tests__/fixtures/fixtures/fixtureOutputExt/options.json
- src/__tests__/fixtures/fixtures/fixtureOutputExt/output.js
- src/__tests__/plugin-tester.js
- src/plugin-tester.js
details can be found in issue #72 
---
ps: i was forced to commit via `git commit -no-verify` because otherwise im getting this error:
```
c:\projects\github\babel-plugin-tester>git commit
husky > pre-commit (node v12.16.3)
sh: C:projectsgithubbabel-plugin-testernode_modules.binkcd-scripts.CMD: command not found
husky > pre-commit hook failed (add --no-verify to bypass)
```
(im guessing, that something is stripping `\` from path and also i dont have file
`C:\projects\github\babel-plugin-tester\node_modules\.binkcd-scripts.CMD` on my pc even after deleting node_modules and caling `npm install` again ... , also i have no idea what `husky` is ...)
OS: `windows 10 v 1909 build 18363.836`
npm -v: `6.14.4`
node -v: `v12.16.3`
> added 'fixtureOutputExt' configuration option

- README.md
- src/__tests__/__snapshots__/plugin-tester.js.snap
- src/__tests__/plugin-tester.js
- src/plugin-tester.js
**What**: remove inference. Default to "unknown plugin" 
**Why**: Closes #60
**How**: Remove logic and tests related to inference.
cc @jayphelps, what do you think? I don't think we need a major version bump here because nobody's build should break with this change.
> fix(pluginNameInference): remove inference. Default to "unknown plugin"

- README.md
After these changes: https://github.com/babel-utils/babel-plugin-tester/commit/91c22ecc29598db2a99b16df29d986087e9cd1b4
It's no longer true that `pluginName` is unnecessary :-)
> Update comment regarding pluginName in full example

- src/__tests__/plugin-tester.js
- src/plugin-tester.js
Fixes https://github.com/babel-utils/babel-plugin-tester/issues/83
**What**:
Uses `babel.transformAsync` by default.
**Why**:
To support async babel plugins.
**How**:
Check for the existence of `babel.transformAsync`, and fall back to `babel.transform` if necessary.
> use babel.transformAsync when it's available

- src/__tests__/__snapshots__/plugin-tester.js.snap
- src/__tests__/fixtures/fixtureOutputExt/fixture/code.ts
- src/__tests__/fixtures/fixtureOutputExt/fixture/options.json
- src/__tests__/fixtures/fixtureOutputExt/fixture/output.js
- src/__tests__/fixtures/root-fixtureOutputExt/root/fixture/code.ts
- src/__tests__/fixtures/root-fixtureOutputExt/root/fixture/output.js
- src/__tests__/fixtures/root-fixtureOutputExt/root/options.json
- src/__tests__/plugin-tester.js
- src/plugin-tester.js
**What**: The `fixtureOutputExt` option works when it appears in a local `options.json` file but is ignored if it appears in a root `options.json` file even though [the docs claim that root options.json configurations are inherited](https://github.com/babel-utils/babel-plugin-tester#fixtures). This PR ensures `fixtureOutputExt` is no longer ignored in root `options.json`.
**Why**: Sometimes it's necessary to specify different values for `fixtureOutputExt` across different fixtures. Other times, like when working in TypeScript projects, it's nice to be able to specify a single overridable default (like `.js` or `.mjs`) in one place instead of across ~100 otherwise-empty `options.json` files nestled away in fixture subdirectories.
**How**: By ensuring `fixtureOutputExt` is [pulled from the …
> fix(src): fix fixtureOutputExt being ignored in root options.json

- src/__tests__/plugin-tester.js
- src/plugin-tester.js
Closes #74
**What**: As stated in #74, plugins are run in a different order in fixtures vs in tests. I confirmed this behavior with a [new unit test](https://github.com/babel-utils/babel-plugin-tester/compare/master...Xunnamius:babel-plugin-tester:contrib-fix-plugin-run-order-for-fixtures?expand=1#diff-253e8230e711a2052517dc6d606c4485422291d9aef90b8bcde6086fa2cbf78aR732-R765). This PR fixes the problem.
**Why**: Aside from being unlike how babel would invoke the plugin in real life, running plugins in inconsistent sequences can lead to [surprising behavior](https://github.com/babel-utils/babel-plugin-tester/issues/74) and brittle tests. Also, it makes [specifying a consistent custom plugin loading order](https://github.com/babel-utils/babel-plugin-tester/pull/91) more difficult to reason …
> fix(src): fix plugin run order for fixtures to match tests

- src/__tests__/plugin-tester.js
- src/index.js
- src/plugin-tester.js
Closes #76
Solves #18
**What**: As requested in #76, this PR allows users to specify in what order babel will run the plugin under test with respect to the plugins passed via `options.babelOptions.plugins`.
**Why**: Sometimes you need a plugin to run before certain plugins but/or after others, as demonstrated in #76.
**How**: Users can import a [symbol well-known to babel-plugin-tester](https://github.com/babel-utils/babel-plugin-tester/compare/master...Xunnamius:babel-plugin-tester:contrib-feat-arbitrary-run-order?expand=1#diff-493fa057af0f000faf7ce45becbbe2ced9bab231e9e357e70dd00d62beea0710R8) that, if encountered in `options.babelOptions.plugins`, [will be replaced by the plugin under test](https://github.com/babel-utils/babel-plugin-tester/compare/master...Xunnamius:babel-plugin-tester …
> feat(src): add support for arbitrary run order of plugin under test

- package.json
- src/__tests__/plugin-tester.js
- src/plugin-tester.js
**What**: This PR brings back the `pluginName` inference functionality that was removed in #78. The new inference functionality is "lightweight" (in that it never throws or emits an error upon failure), addresses the concerns raised in #58 and #60, and maintains the `"unknown plugin"` determination as a fallback.
Also, even though this PR probably doesn't break anything since it falls back to the current `"unknown plugin"` functionality upon failure, it might be considered a breaking change for the same reason #78 was.
**Why**: Because the developer experience was greatly improved by `pluginName` inference in my personal experience. I have a lot of shared/copy-pasted configurations, and it can be easy to forget to change the `pluginName` value manually when switching between babel plugin …
> feat(src): bring back (lightweight) plugin name inference
